### ISSUE TITLE
Reproduce each experiment in the paper (experiment folder) in Jupyter notebooks.

### ISSUE THREAD

**Issue by jdey4** [neurodata/ProgLearn#41] opened 2020-08-07 19:52 UTC
Describe each step and render it like a tutorial.

**Comment by jdey4** [comment] 2020-08-11 14:34
Same as #38, so closing #38

**Comment by PSSF23** [comment] 2020-09-02 17:18
I wish to work on the issue during my sprint 0. May I get more information about which experiments need to be modified and what standard procedures I need to follow? Thank you!

**Comment by ykobaya9** [comment] 2020-09-02 17:56
Hi, I was also one of the people who wanted to work on this issue. Could I do the CIFAR dataset? Thank you!

**Comment by jdey4** [comment] 2020-09-09 18:06
Follow the style here: https://github.com/neurodata/hyppo/blob/master/docs/tutorials/independence/independence.ipynb

**Comment by levinwil** [comment] 2020-10-12 21:23
Closing, since this is a duplicate of #286 with less information

**Closed by levinwil** 2020-10-12 21:23 UTC
Labels: ndd
